/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbs.view;


import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import sgbs.controller.UsuarioController;
import sgbs.dao.ExceptionDAO;
import sgbs.model.Usuario;

/**
 *
 * @author gabriel
 */
public class TelaPerfilUsuario extends javax.swing.JInternalFrame {
    public static Usuario usuario;
    /**
     * Creates new form TelaPerfilUsuario
     */
    public TelaPerfilUsuario() {
        initComponents();
        atualizaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFunc = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSobrenome = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNomeDeUsuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordFieldSenhaAtual = new javax.swing.JPasswordField();
        jPasswordFieldNovaSenha = new javax.swing.JPasswordField();
        jPasswordFieldConfirmNovaSenha = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxAcessoLab = new javax.swing.JComboBox<>();
        jComboBoxAdmin = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        jPasswordField4.setText("jPasswordField4");

        jLabel11.setText("jLabel11");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setResizable(true);
        setTitle("SGBS - MEU PERFIL");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/usuario.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel3.setText("Sobrenome:");

        jLabel4.setText("Funcional");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel12.setText("Nome de Usuário:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSobrenome))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeDeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNomeDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Acesso"));

        jLabel5.setText("Senha atual");

        jLabel6.setText("Nova senha");

        jLabel7.setText("Confirmação de senha");

        jPasswordFieldSenhaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaAtualActionPerformed(evt);
            }
        });

        jLabel9.setText("Acesso Laboratório");

        jLabel10.setText("Administrador");

        jComboBoxAcessoLab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jComboBoxAcessoLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAcessoLabActionPerformed(evt);
            }
        });

        jComboBoxAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jPasswordFieldSenhaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldNovaSenha)
                    .addComponent(jPasswordFieldConfirmNovaSenha))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxAcessoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addComponent(jLabel10)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldConfirmNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAcessoLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalvar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAcessoLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAcessoLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAcessoLabActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:);
        if (txtSobrenome.getText().equals(usuario.getSobrenome()) && txtNome.getText().equals(usuario.getNome())
            && txtNomeDeUsuario.getText().equals(usuario.getNomeDeUsuario()) && jPasswordFieldSenhaAtual.getText().equals("")
                && jPasswordFieldNovaSenha.getText().equals("") && jPasswordFieldConfirmNovaSenha.getText().equals("") &&
                jComboBoxAdmin.getSelectedItem().toString().equals(usuario.getAdmin()) && jComboBoxAcessoLab.getSelectedItem().toString().equals(usuario.getAcessoLab())) 
        {
            JOptionPane.showMessageDialog(this, "Nada foi alterado!", "Saindo", JOptionPane.INFORMATION_MESSAGE);
        
        
        } else {
            // SE OS ACESSOS CONTINUAM IGUAIS NAO É NECESSAORIO VALIDACAO DO ADMINISTRADOR
            if (jComboBoxAdmin.getSelectedItem().toString().equals(usuario.getAdmin()) && jComboBoxAcessoLab.getSelectedItem().toString().equals(usuario.getAcessoLab())) 
            { 
                alteraDados();
                atualizaCampos();
            
            } else // OS DADOS DE ACESSO FORAM ALTERADOS, NECESSARIO PERMISAO DO ADMINISTRADOR
            { 
                String novoAcessoLab = jComboBoxAcessoLab.getSelectedItem().toString();
                String novoAdmin = jComboBoxAdmin.getSelectedItem().toString();
                
                try {
                    if (validaAdm()) {
                        usuario.setAcessoLab(novoAcessoLab);
                        usuario.setAdmin(novoAdmin);
                        alteraDados();
                        atualizaCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Não possível atualizar suas permissões de acesso", "Administrador inválido", JOptionPane.ERROR_MESSAGE);
                        
                    }
                } catch (ExceptionDAO ex) {
                    JOptionPane.showMessageDialog(this,"Erro ao validar administrador\nErro: " + ex, "ERRO", JOptionPane.ERROR_MESSAGE);

                }
                
            }
        }
            
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jPasswordFieldSenhaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaAtualActionPerformed

    private void alteraDados() {
        UsuarioController usuarioController = new UsuarioController();
        // PEGANDO NOME E SOBRENOME
        usuario.setNome(txtNome.getText());
        usuario.setSobrenome(txtSobrenome.getText());

        // VERIFICANDO SE O NOME DE USUARIO JÁ EXISTE
        if (!txtNomeDeUsuario.getText().equals(usuario.getNomeDeUsuario())) {
            try {
                if(!usuarioController.nomeDeUsuarioJaExiste(txtNomeDeUsuario.getText())) {
                    usuario.setNomeDeUsuario(txtNomeDeUsuario.getText());

                } else {
                    JOptionPane.showMessageDialog(this, "Nome de Usuário Indisponível", "ERRO", JOptionPane.ERROR_MESSAGE);

                }
            } catch (ExceptionDAO ex) {
                JOptionPane.showMessageDialog(this, "ERRO AO CONSULTAR NOME DE USUARIO\nERRO: " + ex, "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }

        // VERIRIFICANDO A SENHA ATUAL DO USUARIO
        if (jPasswordFieldSenhaAtual.getText().equals(usuario.getSenha())) {
            // VERIFICANDO SE A NOVA SENHA E CONFIRMAÇÃO DE SENHA SÃO IGUAIS
            if(jPasswordFieldNovaSenha.getText().equals("") && jPasswordFieldConfirmNovaSenha.getText().equals("")) 
            {
                try {
                    usuarioController.atulizarUsuario(usuario);
                    JOptionPane.showMessageDialog(this, "Dados Atulizados!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);

                } catch (ExceptionDAO ex) {
                    JOptionPane.showMessageDialog(this, "ERRO AO ATUALIZAR USUARIO\nERRO: " + ex, "ERRO", JOptionPane.ERROR_MESSAGE);

                }
            } else if (jPasswordFieldNovaSenha.getText().equals(jPasswordFieldConfirmNovaSenha.getText())) 
            {
                try {
                    usuario.setSenha(jPasswordFieldNovaSenha.getText());
                    usuarioController.atulizarUsuario(usuario);
                    JOptionPane.showMessageDialog(this, "Dados Atulizados!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);

                } catch (ExceptionDAO ex) {
                    JOptionPane.showMessageDialog(this, "ERRO AO ATUALIZAR USUARIO\nERRO: " + ex, "ERRO", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(this, "As novas senhas não conferem!", "ERRO", JOptionPane.ERROR_MESSAGE);

            }

        }
        else {
            JOptionPane.showMessageDialog(this, "Senha Incorreta", "ERRO", JOptionPane.ERROR_MESSAGE);

        }
    }
    
    private boolean validaAdm() throws ExceptionDAO {
        UsuarioController usuarioController = new UsuarioController();
        boolean validado = false;
        JTextField usr = new JTextField(5);
        JPasswordField senha = new JPasswordField(5);

        JPanel panelValidaAdm = new JPanel();
        panelValidaAdm.add(new JLabel("Usuário:"));
        panelValidaAdm.add(usr);
        panelValidaAdm.add(Box.createHorizontalStrut(5)); // espaço
        panelValidaAdm.add(new JLabel("Senha:"));
        panelValidaAdm.add(senha);

        int result = JOptionPane.showConfirmDialog(null, panelValidaAdm, 
               "VALIDAÇÃO DE ADMINISTRADOR", JOptionPane.OK_CANCEL_OPTION);
      
        if (result == JOptionPane.OK_OPTION) {
            validado = usuarioController.validarUsuarioAdmin(usr.getText(), senha.getText());
        }
        return validado;
        
    }
    
    private void atualizaCampos() {
        // ALTERANDO CAMPOS COM INFORMAÇÕES DO USUÁRIO ATUAL
        txtNome.setText(usuario.getNome());
        txtSobrenome.setText(usuario.getSobrenome());
        txtNomeDeUsuario.setText(usuario.getNomeDeUsuario());
        lblFunc.setText(usuario.getNumeroFuncional());
        
        if (usuario.getAcessoLab().toUpperCase().equals("SIM"))
            jComboBoxAcessoLab.setSelectedItem("Sim");
        else 
            jComboBoxAcessoLab.setSelectedItem("Não");
        
        if (usuario.getAdmin().toUpperCase().equals("SIM"))
            jComboBoxAdmin.setSelectedItem("Sim");
        else 
            jComboBoxAdmin.setSelectedItem("Não");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBoxAcessoLab;
    private javax.swing.JComboBox<String> jComboBoxAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordFieldConfirmNovaSenha;
    private javax.swing.JPasswordField jPasswordFieldNovaSenha;
    private javax.swing.JPasswordField jPasswordFieldSenhaAtual;
    private javax.swing.JLabel lblFunc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeDeUsuario;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
