/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbs.view;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import sgbs.controller.TriagemController;
import sgbs.dao.ExceptionDAO;
import sgbs.model.Doador;

/**
 *
 * @author gabriel
 */

public class TelaTriagem extends javax.swing.JFrame {
    private final Doador doador;
    private static String  cpfDoador;
    private static Integer idDoador;
    private static boolean aprovadoTriagem;
    
        
        

    /**
     * Creates new form Tela
     */
    public TelaTriagem() throws ExceptionDAO {
        initComponents();
        this.setLocationRelativeTo(null); // CENTRALIZA
        btnResultado.setEnabled(false);
        
        // CARREGANDO DADOS DOADORs
        if(idDoador != null) {
            doador = sgbs.dao.DoadorDAO.carregarDadosDoador(idDoador);
            TelaCadastrarDoacao.setIdDoador(idDoador);
        } else {
            doador = sgbs.dao.DoadorDAO.carregarDadosDoador(cpfDoador);
            TelaCadastrarDoacao.setCpfDoador(cpfDoador);
        }
            
        
        txtNomeDoador.setText(doador.getNome()  + " " + doador.getSobrenome());
        txtIdDoador.setText(doador.getIdDoador().toString());
        txtDtNasc.setText(doador.getDtNasc());
        txtTipoSanguineo.setText(doador.getTipoSanguineo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeDoador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDtNasc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTipoSanguineo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdDoador = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxCirOdontologica = new javax.swing.JComboBox<>();
        jComboBoxEvidenciaAids = new javax.swing.JComboBox<>();
        jComboBoxHepatiteBouC = new javax.swing.JComboBox<>();
        jComboBoxTeveHepatite = new javax.swing.JComboBox<>();
        jComboBoxTeveCancer = new javax.swing.JComboBox<>();
        jComboBoxDrogasIlicitas = new javax.swing.JComboBox<>();
        jComboBoxDoencaChagas = new javax.swing.JComboBox<>();
        jComboBoxDiabetico = new javax.swing.JComboBox<>();
        jComboBoxTeveMalaria = new javax.swing.JComboBox<>();
        jComboBoxTransplateOrgaos = new javax.swing.JComboBox<>();
        jComboBoxTratDentario = new javax.swing.JComboBox<>();
        jComboBoxProblemasPulmaoCoracaoRinsFig = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btnResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGBS - TRIAGEM");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Doador"));

        jLabel1.setText("Nome: ");

        txtNomeDoador.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        txtNomeDoador.setText("jLabel2");

        jLabel2.setText("Data de Nascimento");

        txtDtNasc.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        jLabel4.setText("Tipo Sanguíneo: ");

        txtTipoSanguineo.setForeground(new java.awt.Color(255, 0, 0));

        jLabel10.setText("ID DOADOR: ");

        txtIdDoador.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 370, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNomeDoador)
                        .addComponent(jLabel10))
                    .addComponent(txtIdDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTipoSanguineo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Triagem - Perguntas"));

        jLabel3.setText("O(a) doador(a)  teve hepatite após os 11 anos de idade ?");

        jLabel5.setText("O(a) doador(a)  possui evidências clínicas ou laboratoriais de Hepatite B ou C?");

        jLabel6.setText("O(a) doador(a)  possui evidências clínicas ou laboratoriais de aids (vírus HIV) ?");

        jLabel7.setText("O(a) doador(a)  relatou o uso de drogas ilícitas injetáveis ?");

        jLabel8.setText("O(a) doador(a)  possui doença de Chagas ? ");

        jLabel9.setText("O(a) doador(a)  já teve ou possui câncer (incluindo leucemia) ?");

        jLabel11.setText("O(a) doador(a)  já teve malária ?");

        jLabel14.setText("O(a) doador(a) foi submetido a transplante de órgãos ou de medula ?");

        jLabel15.setText("O(a) doador(a) tem graves problemas no pulmão, coração, rins ou fígado ?");

        jLabel16.setText(" O(a) doador(a) é diabético com complicações vasculares ou em uso de insulina ?");

        jLabel17.setText("O(a) doador(a) fez algum tratamento dentário recentemente ?");

        jComboBoxCirOdontologica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));
        jComboBoxCirOdontologica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCirOdontologicaItemStateChanged(evt);
            }
        });
        jComboBoxCirOdontologica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCirOdontologicaActionPerformed(evt);
            }
        });

        jComboBoxEvidenciaAids.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jComboBoxHepatiteBouC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jComboBoxTeveHepatite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jComboBoxTeveCancer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));
        jComboBoxTeveCancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTeveCancerActionPerformed(evt);
            }
        });

        jComboBoxDrogasIlicitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jComboBoxDoencaChagas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jComboBoxDiabetico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jComboBoxTeveMalaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));
        jComboBoxTeveMalaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTeveMalariaActionPerformed(evt);
            }
        });

        jComboBoxTransplateOrgaos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jComboBoxTratDentario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jComboBoxProblemasPulmaoCoracaoRinsFig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jLabel19.setText("O(a) doador(a) realizou alguma cirurgia odontológica com anestesia geral?");

        btnResultado.setText("Resultado Triagem");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxProblemasPulmaoCoracaoRinsFig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTransplateOrgaos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxDoencaChagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEvidenciaAids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxDrogasIlicitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTeveCancer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxDiabetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxTratDentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addGap(0, 101, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTeveHepatite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxHepatiteBouC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTeveMalaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jComboBoxCirOdontologica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnResultado)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTeveHepatite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jComboBoxHepatiteBouC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEvidenciaAids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDrogasIlicitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDoencaChagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTeveCancer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(jComboBoxTeveMalaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTransplateOrgaos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxProblemasPulmaoCoracaoRinsFig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDiabetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTratDentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCirOdontologica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResultado)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCirOdontologicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCirOdontologicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCirOdontologicaActionPerformed

    private void jComboBoxTeveCancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTeveCancerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTeveCancerActionPerformed

    private void jComboBoxTeveMalariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTeveMalariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTeveMalariaActionPerformed
    // BTN CADASTRA A TRIAGEM 
    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        Integer idUsuario = TelaPrincipalMDI.usuario.getIdUsuario();
        TriagemController triagemController = new TriagemController();
        Boolean algumJBoxSemResposta;
       
        // ADICIONANDO JCOMBOX NO ARRAY
        ArrayList<JComboBox> jboxArray = new ArrayList<JComboBox>();
        jboxArray.add(jComboBoxTeveHepatite);
        jboxArray.add(jComboBoxHepatiteBouC);
        jboxArray.add(jComboBoxEvidenciaAids);
        jboxArray.add(jComboBoxDrogasIlicitas);
        jboxArray.add(jComboBoxDoencaChagas);
        jboxArray.add(jComboBoxTeveCancer);
        jboxArray.add(jComboBoxTeveMalaria);
        jboxArray.add(jComboBoxTransplateOrgaos);
        jboxArray.add(jComboBoxProblemasPulmaoCoracaoRinsFig);
        jboxArray.add(jComboBoxDiabetico);
        jboxArray.add(jComboBoxTratDentario);
        jboxArray.add(jComboBoxCirOdontologica);
        
        // VERIFICANDO SE ALGUM COMBOX ESTA SEM RSPOSTA
        algumJBoxSemResposta = comboBoxSemResposta(jboxArray);
        
        if (!algumJBoxSemResposta) {
            try {
                aprovadoTriagem = triagemController.resultadoTriagem(idUsuario, idDoador,
                        retornaTrueFalse(jComboBoxTeveHepatite),  retornaTrueFalse(jComboBoxHepatiteBouC),
                        retornaTrueFalse(jComboBoxEvidenciaAids), retornaTrueFalse(jComboBoxDrogasIlicitas),
                        retornaTrueFalse(jComboBoxDoencaChagas), retornaTrueFalse(jComboBoxTeveCancer),
                        retornaTrueFalse(jComboBoxTeveMalaria), retornaTrueFalse(jComboBoxTransplateOrgaos),
                        retornaTrueFalse(jComboBoxProblemasPulmaoCoracaoRinsFig), retornaTrueFalse(jComboBoxDiabetico),
                        retornaTrueFalse(jComboBoxTratDentario), retornaTrueFalse(jComboBoxCirOdontologica));
            } catch (ExceptionDAO ex) {
                JOptionPane.showMessageDialog(null,"ERRO AO RECEBER RESULTADO DA TRIAGEM\nERRO"+ex, 
                        "ERRO", JOptionPane.ERROR_MESSAGE);

            }
        } else 
        {
            JOptionPane.showMessageDialog(null,"Responda a todas perguntas", "Atenção", JOptionPane.ERROR_MESSAGE);

        }
        
        if (aprovadoTriagem) {
           JOptionPane.showMessageDialog(null,triagemController.getResultado() +"\n"+ triagemController.getMotivo(), "Resultado", JOptionPane.INFORMATION_MESSAGE);
           TelaCadastrarDoacao telaCadastrarDoacao;
            try {
                telaCadastrarDoacao = new TelaCadastrarDoacao();
                telaCadastrarDoacao.setVisible(true);
            } catch (ExceptionDAO ex) {
                    JOptionPane.showMessageDialog(null,"ERRO AO INICIALIZAR TELA DE CADASTRO DE NOVA DOAÇÃO - Na Classe Triagem\nERRO: " + ex, "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null,triagemController.getResultado() +"\n"+ triagemController.getMotivo(), "Resultado", JOptionPane.INFORMATION_MESSAGE);
        }
        this.dispose();
        

        
    }//GEN-LAST:event_btnResultadoActionPerformed

    private void jComboBoxCirOdontologicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCirOdontologicaItemStateChanged
        // TODO add your handling code here:
        if (!jComboBoxCirOdontologica.getSelectedItem().equals("Selecione")) {
            btnResultado.setEnabled(true);
        }else {
            btnResultado.setEnabled(false);
        }        
    }//GEN-LAST:event_jComboBoxCirOdontologicaItemStateChanged
    // USADO PARA RETORNAR SE O ITEM DO COMBOBOX É "SIM" 
    private boolean retornaTrueFalse (JComboBox jbox) {
        if(jbox.getSelectedItem().equals("Sim")){
            return true;
        }
        return false;
    }
    
    // USADO PARA VERTIFICAR SE HÁ ALGUM COMBOBOM COM O ITEM = "SELECIONE" - SEM RESPOSTA
    private boolean comboBoxSemResposta(ArrayList<JComboBox> jbox) {
        boolean achouSemResposta = false;
        for (JComboBox i : jbox) {
            if(i.getSelectedItem().equals("Selecione")) {
                achouSemResposta = true;
                break;
                
            }
        }
        return achouSemResposta;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaTriagem().setVisible(true);
                } catch (ExceptionDAO ex) {
                    JOptionPane.showMessageDialog(null,"ERRO AO INICIALIZAR TELA DE TRIAGEM\nERRO: " + ex, "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResultado;
    private javax.swing.JComboBox<String> jComboBoxCirOdontologica;
    private javax.swing.JComboBox<String> jComboBoxDiabetico;
    private javax.swing.JComboBox<String> jComboBoxDoencaChagas;
    private javax.swing.JComboBox<String> jComboBoxDrogasIlicitas;
    private javax.swing.JComboBox<String> jComboBoxEvidenciaAids;
    private javax.swing.JComboBox<String> jComboBoxHepatiteBouC;
    private javax.swing.JComboBox<String> jComboBoxProblemasPulmaoCoracaoRinsFig;
    private javax.swing.JComboBox<String> jComboBoxTeveCancer;
    private javax.swing.JComboBox<String> jComboBoxTeveHepatite;
    private javax.swing.JComboBox<String> jComboBoxTeveMalaria;
    private javax.swing.JComboBox<String> jComboBoxTransplateOrgaos;
    private javax.swing.JComboBox<String> jComboBoxTratDentario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtDtNasc;
    private javax.swing.JLabel txtIdDoador;
    private javax.swing.JLabel txtNomeDoador;
    private javax.swing.JLabel txtTipoSanguineo;
    // End of variables declaration//GEN-END:variables
    
    // GETTERS E SETTERS 
    public static String getCpfDoador() {
        return cpfDoador;
    }

    public static void setCpfDoador(String cpfDoador) {
        TelaTriagem.cpfDoador = cpfDoador;
    }

    public static Integer getIdDoador() {
        return idDoador;
    }

    public static void setIdDoador(Integer idDoador) {
        TelaTriagem.idDoador = idDoador;
    }

    public static boolean isAprovadoTriagem() {
        return aprovadoTriagem;
    }
    

}
