package sgbs.view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import sgbs.controller.DoacaoController;
import javax.swing.JOptionPane;
import sgbs.dao.ExceptionDAO;
import sgbs.model.Doador;

/**
 *
 * @author gabriel
 */
public class TelaCadastrarDoacao extends javax.swing.JFrame {
    private final Doador doador;
    private static String  cpfDoador;
    private static Integer idDoador;
    
    
    // DATA E HORA
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    Date date = new Date();
    String data = dateFormat.format(date);
    
    /**
     * Creates new form TelaCadastrarDoacao1
     */
    public TelaCadastrarDoacao() throws ExceptionDAO {
        initComponents();
        this.setLocationRelativeTo(null); // CENTRALIZA
        if(idDoador != null) {
            doador = sgbs.dao.DoadorDAO.carregarDadosDoador(idDoador);
        } else {
            doador = sgbs.dao.DoadorDAO.carregarDadosDoador(cpfDoador);
        }
        
        txtNomeDoador.setText(doador.getNome() + " " + doador.getSobrenome());
        txtTipoSanguineo.setText(doador.getTipoSanguineo());
        this.setTitle("SGBS - NOVA DOAÇÃO | " + data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInformacoesDoacao = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerQtdColetada = new javax.swing.JSpinner();
        txtTipoSanguineo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeDoador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarDoacao = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelInformacoesDoacao.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setText("ml");

        jSpinnerQtdColetada.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        txtTipoSanguineo.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        txtTipoSanguineo.setText("TS do doador");

        jLabel3.setText("Grupo sanguíneo");

        jLabel4.setText("Quantidade coletada");

        txtNomeDoador.setText("Nome do doador aqui");

        jLabel1.setText("Doador");

        btnCadastrarDoacao.setText("Cadastrar");
        btnCadastrarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDoacaoActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInformacoesDoacaoLayout = new javax.swing.GroupLayout(jPanelInformacoesDoacao);
        jPanelInformacoesDoacao.setLayout(jPanelInformacoesDoacaoLayout);
        jPanelInformacoesDoacaoLayout.setHorizontalGroup(
            jPanelInformacoesDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesDoacaoLayout.createSequentialGroup()
                .addGroup(jPanelInformacoesDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelInformacoesDoacaoLayout.createSequentialGroup()
                        .addGroup(jPanelInformacoesDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoSanguineo)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelInformacoesDoacaoLayout.createSequentialGroup()
                        .addComponent(jSpinnerQtdColetada, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarDoacao)))
                .addContainerGap())
        );
        jPanelInformacoesDoacaoLayout.setVerticalGroup(
            jPanelInformacoesDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesDoacaoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeDoador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoSanguineo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInformacoesDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerQtdColetada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacoesDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInformacoesDoacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadastrarDoacao)
                            .addComponent(btnCancel))
                        .addComponent(jLabel5)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInformacoesDoacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInformacoesDoacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDoacaoActionPerformed
        // TODO add your handling code here:
        try {
            boolean sucesso;
            DoacaoController doacaoController = new DoacaoController();

            sucesso = doacaoController.cadastrarDoacao(Float.parseFloat(jSpinnerQtdColetada.getValue().toString()), data.substring(0, 10), "Aguardando Analise", TelaPrincipalMDI.usuario.getIdUsuario(), doador.getCPF(), doador.getIdDoador(), doador.getTipoSanguineo());

            if(sucesso) {
                JOptionPane.showMessageDialog(null, "Doação cadastrada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Campos Não foram preenchidos corretamente !!!", "Tente novamente", JOptionPane.ERROR_MESSAGE);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "ERRO: " + e);
        }
    }//GEN-LAST:event_btnCadastrarDoacaoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCadastrarDoacao().setVisible(true);
                } catch (ExceptionDAO ex) {
                    JOptionPane.showMessageDialog(null,"ERRO AO INICIALIZAR TELA DE CADASTRAR NOVA DOAÇÃO - Na Classe CadastrarDoacao\nERRO: " + ex, "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarDoacao;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelInformacoesDoacao;
    private javax.swing.JSpinner jSpinnerQtdColetada;
    private javax.swing.JLabel txtNomeDoador;
    private javax.swing.JLabel txtTipoSanguineo;
    // End of variables declaration//GEN-END:variables
    
    // GETTERS E SETTERS
    public static String getCpfDoador() {
        return cpfDoador;
    }

    public static void setCpfDoador(String cpfDoador) {
        TelaCadastrarDoacao.cpfDoador = cpfDoador;
    }

    public static Integer getIdDoador() {
        return idDoador;
    }

    public static void setIdDoador(Integer idDoador) {
        TelaCadastrarDoacao.idDoador = idDoador;
    }   

}
