/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbs.view;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import sgbs.dao.ExceptionDAO;
import sgbs.model.Usuario;

/**
 *
 * @author gabriel
 */
public class TelaPrincipalMDI extends javax.swing.JFrame {
    public static String nomeUsuario;
    public static Usuario usuario;
    /**
     * Creates new form TelaPrincipal
     * @throws sgbs.dao.ExceptionDAO
     */
    public TelaPrincipalMDI() throws ExceptionDAO {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        usuario = sgbs.dao.UsuarioDAO.carregarDadosUsuario(nomeUsuario);
        this.setTitle("SGBS | Bem-Vindo " + usuario.getNomeDeUsuario().toUpperCase());
    }
    
    // METODO PARA CENTRALIZAR OS JINTERNALFRAME NO CENTRO DA TELA
    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = jDesktopPane2.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
        (desktopSize.height - jInternalFrameSize.height) / 2);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_novaDoacao = new javax.swing.JMenu();
        jMenuItem_novaDoacao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_pesquisarDoador = new javax.swing.JMenuItem();
        jMenu_novoPedido = new javax.swing.JMenu();
        jMenuItem_novoPedido = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemAcessarEstoque = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemAcessarAreaLab = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemMeuPerfil = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BEM VINDO NomeUsuario");

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jMenu_novaDoacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/heart.png"))); // NOI18N
        jMenu_novaDoacao.setText("Doações");
        jMenu_novaDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_novaDoacaoActionPerformed(evt);
            }
        });

        jMenuItem_novaDoacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/heart_add.png"))); // NOI18N
        jMenuItem_novaDoacao.setText("Nova doação");
        jMenuItem_novaDoacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_novaDoacaoMouseClicked(evt);
            }
        });
        jMenuItem_novaDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_novaDoacaoActionPerformed(evt);
            }
        });
        jMenu_novaDoacao.add(jMenuItem_novaDoacao);

        jMenuBar1.add(jMenu_novaDoacao);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/group.png"))); // NOI18N
        jMenu2.setText("Doadores");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem_pesquisarDoador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/pesquisa.png"))); // NOI18N
        jMenuItem_pesquisarDoador.setText("Pesquisar Doador");
        jMenuItem_pesquisarDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_pesquisarDoadorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_pesquisarDoador);

        jMenuBar1.add(jMenu2);

        jMenu_novoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/pencil.png"))); // NOI18N
        jMenu_novoPedido.setText("Pedido");
        jMenu_novoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_novoPedidoActionPerformed(evt);
            }
        });

        jMenuItem_novoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/add.png"))); // NOI18N
        jMenuItem_novoPedido.setText("Novo Pedido");
        jMenuItem_novoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_novoPedidoActionPerformed(evt);
            }
        });
        jMenu_novoPedido.add(jMenuItem_novoPedido);

        jMenuBar1.add(jMenu_novoPedido);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/page_white_copy.png"))); // NOI18N
        jMenu4.setText("Relatório");
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/application_view_tile.png"))); // NOI18N
        jMenu5.setText("Banco de Sangue");

        jMenuItemAcessarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/application_view_tile.png"))); // NOI18N
        jMenuItemAcessarEstoque.setText("Acessar Painel");
        jMenuItemAcessarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcessarEstoqueActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemAcessarEstoque);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/application_view_list.png"))); // NOI18N
        jMenu6.setText("Laboratório");

        jMenuItemAcessarAreaLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/lock_go.png"))); // NOI18N
        jMenuItemAcessarAreaLab.setText("Acessar");
        jMenuItemAcessarAreaLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcessarAreaLabActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemAcessarAreaLab);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/user.png"))); // NOI18N
        jMenu7.setText("Usuário");

        jMenuItemMeuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/user_edit.png"))); // NOI18N
        jMenuItemMeuPerfil.setText("Meu Perfil");
        jMenuItemMeuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMeuPerfilActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemMeuPerfil);

        jMenuBar1.add(jMenu7);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/door_out.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuSairMenuSelected(evt);
            }
        });
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgbs/images/door_out.png"))); // NOI18N
        jMenuItemSair.setText("Sair do Sistema");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_novaDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_novaDoacaoActionPerformed
        
    }//GEN-LAST:event_jMenu_novaDoacaoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem_novaDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_novaDoacaoActionPerformed
      TelaValidacaoDoador telaNovaDoacao = new TelaValidacaoDoador();
      jDesktopPane2.add(telaNovaDoacao);
      centralizaForm(telaNovaDoacao);
      telaNovaDoacao.setVisible(true);
    
    }//GEN-LAST:event_jMenuItem_novaDoacaoActionPerformed

    private void jMenu_novoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_novoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_novoPedidoActionPerformed

    private void jMenuItem_novoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_novoPedidoActionPerformed
        // TODO add your handling code here:
        TelaPedido telaPedido = new TelaPedido();
        jDesktopPane2.add(telaPedido);
        centralizaForm(telaPedido);
        telaPedido.setVisible(true);
    }//GEN-LAST:event_jMenuItem_novoPedidoActionPerformed

    private void jMenuItem_novaDoacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_novaDoacaoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem_novaDoacaoMouseClicked

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuSairMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuSairMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSairMenuSelected

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        int opcao;
        opcao = JOptionPane.showConfirmDialog(this, "Deseja Sair?", "Sair do Sistema", JOptionPane.YES_NO_OPTION);
        
        if (opcao == 0) {
            this.dispose();
        }
            
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemAcessarAreaLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcessarAreaLabActionPerformed
        // VALIDANDO SE O USUARIO POSSUI ACESSO AO LAB
        if(usuario.getAcessoLab().toUpperCase().equals("SIM")) {
            TelaDoacoesAtuais telaDoacoesAtuais;
            try {
                TelaDoacoesAtuais.setUsuarioNome(usuario.getNomeDeUsuario());
                telaDoacoesAtuais = new TelaDoacoesAtuais();
                jDesktopPane2.add(telaDoacoesAtuais);
                centralizaForm(telaDoacoesAtuais);
                telaDoacoesAtuais.setVisible(true);
            } catch (ExceptionDAO ex) {
                JOptionPane.showMessageDialog(this,"ERRO INTERNO AO ABRIR TELA NOVAS DOAÇÕES\nERRO: " + ex, "ACESSO NEGADO", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            JOptionPane.showMessageDialog(this,"Você Não possui acesso a essa área do sistema", "ACESSO NEGADO", JOptionPane.ERROR_MESSAGE);
        } 
        
    }//GEN-LAST:event_jMenuItemAcessarAreaLabActionPerformed

    private void jMenuItemAcessarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcessarEstoqueActionPerformed
        // TODO add your handling code here:
        TelaEstoque telaEstoque;
        try {
            telaEstoque = new TelaEstoque();
            jDesktopPane2.add(telaEstoque);
            centralizaForm(telaEstoque);
            telaEstoque.setVisible(true);
        } catch (ExceptionDAO ex) {
            JOptionPane.showMessageDialog(this,"ERRO INTERNO AO ABRIR TELA PAINEL DO BANCO DE SANGUE\nERRO: " + ex, "ACESSO NEGADO", JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_jMenuItemAcessarEstoqueActionPerformed

    private void jMenuItem_pesquisarDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_pesquisarDoadorActionPerformed
        TelaDoadoresCadastrados telaDoadoresCadastrados = new TelaDoadoresCadastrados();
        jDesktopPane2.add(telaDoadoresCadastrados);
        centralizaForm(telaDoadoresCadastrados);
        telaDoadoresCadastrados.setVisible(true);
    }//GEN-LAST:event_jMenuItem_pesquisarDoadorActionPerformed

    private void jMenuItemMeuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeuPerfilActionPerformed
        // TODO add your handling code here:
        TelaPerfilUsuario.usuario = usuario; // PASSA O USUARIO ATUAL
        TelaPerfilUsuario telaPerfilUsuario = new TelaPerfilUsuario();
        jDesktopPane2.add(telaPerfilUsuario);
        centralizaForm(telaPerfilUsuario);
        telaPerfilUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemMeuPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaPrincipalMDI().setVisible(true);
                } catch (ExceptionDAO ex) {
                    Logger.getLogger(TelaPrincipalMDI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAcessarAreaLab;
    private javax.swing.JMenuItem jMenuItemAcessarEstoque;
    private javax.swing.JMenuItem jMenuItemMeuPerfil;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItem_novaDoacao;
    private javax.swing.JMenuItem jMenuItem_novoPedido;
    private javax.swing.JMenuItem jMenuItem_pesquisarDoador;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenu_novaDoacao;
    private javax.swing.JMenu jMenu_novoPedido;
    // End of variables declaration//GEN-END:variables


}
