/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbs.view;


import javax.swing.JOptionPane;
import sgbs.controller.DoadorController;
import sgbs.dao.ExceptionDAO;
import sgbs.model.Doador;

/**
 *
 * @author gabriel
 */
public class TelaValidacaoDoador extends javax.swing.JInternalFrame {
    Integer idDoador = null;
    String cpf = null, escolhidoParaValidar = null;
    boolean cadastrado = false;
    private Doador doador;
    DoadorController doadorController = new DoadorController();
    /**
     * Creates new form TelaNovaDoacao
     */
    public TelaValidacaoDoador() {
        initComponents();
        txtCpf.setVisible(false);
        jSpinnerIdDoador.setVisible(false);
        jLabelTituloOpcaoValidacao.setText("NENHUMA OPÇÃO SELECIONADA");
        btnValidar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenu1 = new javax.swing.JMenu();
        jPanelValidaDoador = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxOpcaoDeValidacao = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnValidar = new javax.swing.JButton();
        btnCancelConsulta = new javax.swing.JButton();
        txtData = new javax.swing.JLabel();
        jLabelTituloOpcaoValidacao = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jSpinnerIdDoador = new javax.swing.JSpinner();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("jMenu1");

        setClosable(true);
        setTitle("SGBS - PESQUISA DE DOADOR");

        jLabel9.setText("SELECIONE UM OPÇÃO");

        jComboBoxOpcaoDeValidacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "ID Doador", "CPF" }));
        jComboBoxOpcaoDeValidacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxOpcaoDeValidacaoItemStateChanged(evt);
            }
        });
        jComboBoxOpcaoDeValidacao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxOpcaoDeValidacaoPropertyChange(evt);
            }
        });

        btnValidar.setText("Consultar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnCancelConsulta.setText("Cancelar");
        btnCancelConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelConsulta)
                .addGap(18, 18, 18)
                .addComponent(btnValidar)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidar)
                    .addComponent(btnCancelConsulta))
                .addGap(40, 40, 40))
        );

        jLabelTituloOpcaoValidacao.setText("CPF");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jSpinnerIdDoador.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSpinnerIdDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxOpcaoDeValidacao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTituloOpcaoValidacao)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxOpcaoDeValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTituloOpcaoValidacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerIdDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanelValidaDoadorLayout = new javax.swing.GroupLayout(jPanelValidaDoador);
        jPanelValidaDoador.setLayout(jPanelValidaDoadorLayout);
        jPanelValidaDoadorLayout.setHorizontalGroup(
            jPanelValidaDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValidaDoadorLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelValidaDoadorLayout.setVerticalGroup(
            jPanelValidaDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValidaDoadorLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelValidaDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelValidaDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        idDoador = Integer.parseInt(jSpinnerIdDoador.getValue().toString());
        cpf = txtCpf.getText();
        try {
            if(escolhidoParaValidar.equals("cpf")) {
                cadastrado = doadorController.verificarDoador(cpf);
                TelaTriagem.setCpfDoador(cpf);
            } else if (escolhidoParaValidar.equals("id")) {
                cadastrado = doadorController.verificarDoador(idDoador);
                TelaTriagem.setIdDoador(idDoador);
            }
            // O DOADOR FOI ENCONTRADO NO BANCO DE DADOS
            if (cadastrado) { 
                JOptionPane.showMessageDialog(this, "Doador encontrado !!!", "Liberado para inserir nova doação", JOptionPane.INFORMATION_MESSAGE);
                jPanelValidaDoador.setVisible(false);
                
                // PROCESSO DE TRIAGEM

                TelaTriagem triagem = new TelaTriagem();
                triagem.setVisible(true);
                this.dispose();
                
                // OBTENDO DADOS DO DOADOR
                if (escolhidoParaValidar.equals("cpf")) {
                    doador = sgbs.dao.DoadorDAO.carregarDadosDoador(cpf);
                } else if (escolhidoParaValidar.equals("id")) {
                    doador = sgbs.dao.DoadorDAO.carregarDadosDoador(idDoador);
                }
                
                
            } else {
                int opcao;
                opcao = JOptionPane.showConfirmDialog(this, "Deseja Cadastrar um novo doador ?", "Doador Não encontrado", JOptionPane.YES_NO_OPTION);
                
                if (opcao == 0 ) {
                    this.dispose();
                    TelaCadastrarDoador telaCadastrarDoador = new TelaCadastrarDoador();
                    telaCadastrarDoador.setVisible(true);
                }
            }
        } catch (ExceptionDAO ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro\nERRO: " + ex, "Tente novamente", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void jComboBoxOpcaoDeValidacaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxOpcaoDeValidacaoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOpcaoDeValidacaoPropertyChange

    private void jComboBoxOpcaoDeValidacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOpcaoDeValidacaoItemStateChanged
        
        if (jComboBoxOpcaoDeValidacao.getSelectedItem().equals("CPF")) 
        {   
            jLabelTituloOpcaoValidacao.setVisible(true);
            jLabelTituloOpcaoValidacao.setText("Insira o CPF do doador");
            escolhidoParaValidar = "cpf";
            cpf = null;
            jSpinnerIdDoador.setVisible(false);
            txtCpf.setVisible(true);
            btnValidar.setEnabled(true);
    
        } else if (jComboBoxOpcaoDeValidacao.getSelectedItem().equals("ID Doador")) 
        {
            jLabelTituloOpcaoValidacao.setVisible(true);
            jLabelTituloOpcaoValidacao.setText("Insira o ID do doador");
            escolhidoParaValidar = "id";
            idDoador = null;
            txtCpf.setVisible(false);
            jSpinnerIdDoador.setVisible(true);
            btnValidar.setEnabled(true);
           
        } else
        {
            jLabelTituloOpcaoValidacao.setText("NENHUMA OPÇÃO SELECIONADA");
            txtCpf.setVisible(false);
            jSpinnerIdDoador.setVisible(false);
            btnValidar.setEnabled(false);
        }

    }//GEN-LAST:event_jComboBoxOpcaoDeValidacaoItemStateChanged

    private void btnCancelConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelConsultaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelConsultaActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelConsulta;
    private javax.swing.JButton btnValidar;
    private javax.swing.JComboBox<String> jComboBoxOpcaoDeValidacao;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTituloOpcaoValidacao;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelValidaDoador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerIdDoador;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JLabel txtData;
    // End of variables declaration//GEN-END:variables
}
